#!/bin/sh
# ============================================================ 
# Script: file.sh Purpose: - Create dashboard 
# routes under src/app/dashboard - Create 
# page.tsx only if it does NOT exist - POSIX 
# compatible (Acode / busybox safe) 
# ============================================================
DASHBOARD_ROOT="src/app/dashboard" 
create_page() {
  DIR_PATH="$DASHBOARD_ROOT/$1" 
  FILE_PATH="$DIR_PATH/page.tsx" if [ -f 
  "$FILE_PATH" ]; then
    echo "SKIP: $FILE_PATH already exists" 
    return 0
  fi mkdir -p "$DIR_PATH" echo "/**" > 
  "$FILE_PATH" echo " * Route File: 
  $FILE_PATH" >> "$FILE_PATH" echo " * 
  Auto-generated by dashboard route script" 
  >> "$FILE_PATH"
  echo " */" >> "$FILE_PATH" echo "export 
  default function Page() {" >> "$FILE_PATH" 
  echo " return null;" >> "$FILE_PATH" echo 
  "}" >> "$FILE_PATH" echo "CREATED: 
  $FILE_PATH"
}
echo "Creating routes under: $DASHBOARD_ROOT"
# ============================================================ 
# COURSES 
# ============================================================
create_page "courses/enrolled" create_page 
"courses/available" create_page 
"courses/checkout" create_page 
"courses/[courseId]" create_page 
"courses/[courseId]/syllabus" create_page 
"courses/[courseId]/notes" create_page 
"courses/[courseId]/quiz" create_page 
"courses/[courseId]/previous-papers" 
create_page 
"courses/[courseId]/solved-papers" 
create_page "courses/[courseId]/progress"
# ============================================================ 
# QUIZ 
# ============================================================
create_page "quiz/upcoming" create_page 
"quiz/history" create_page "quiz/[quizId]" 
create_page "quiz/[quizId]/attempt" 
create_page "quiz/[quizId]/result"
# ============================================================ 
# NOTES 
# ============================================================
create_page "notes/[subjectId]" create_page 
"notes/[subjectId]/[chapterId]" create_page 
"notes/[subjectId]/[chapterId]/[topicId]"
# ============================================================ 
# SYLLABUS 
# ============================================================
create_page "syllabus/[examId]" create_page 
"syllabus/[examId]/[subjectId]" create_page 
"syllabus/[examId]/[subjectId]/[chapterId]"
# ============================================================ 
# PREVIOUS PAPERS 
# ============================================================
create_page "previous-papers/[year]" 
create_page 
"previous-papers/[year]/[paperId]"
# ============================================================ 
# SOLVED PAPERS 
# ============================================================
create_page "solved-papers/[year]" 
create_page "solved-papers/[year]/[paperId]"
# ============================================================ 
# PROFILE 
# ============================================================
create_page "profile/edit" create_page 
"profile/security"
# ============================================================ 
# SETTINGS 
# ============================================================
create_page "settings/password" create_page 
"settings/notifications"
# ============================================================ 
# OPTIONAL 
# ============================================================
create_page "bookmarks" create_page "history" 
create_page "performance"
echo "Done ✅"
