/**
 * Route File: src/app/dashboard/bookmarks/page.tsx
 * Auto-generated by dashboard route script
 */
"use client";

import React, { useEffect, useState } from 'react';
import Link from 'next/link';

interface Bookmark {
  id: string;
  itemType: string;
  itemId: string;
  createdAt?: string;
}

export default function BookmarksPage() {
  const [bookmarks, setBookmarks] = useState<Bookmark[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/dashboard/bookmarks')
      .then((r) => r.json())
      .then((data) => {
        setBookmarks(data.bookmarks || []);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="p-4 space-y-4 mx-auto">
      <div className="flex items-center mb-4">
        <Link href="/dashboard" className="mr-4 text-gray-600">← Back</Link>
        <h1 className="text-xl font-bold">Bookmarks</h1>
      </div>

      {loading && <div className="text-center text-gray-500">Loading...</div>}

      <div className="space-y-3">
        {bookmarks.map((bm) => (
          <div key={bm.id} className="bg-white border rounded-xl p-4 shadow-sm flex justify-between items-center hover:shadow-md transition">
            <div>
              <h3 className="font-semibold text-gray-800">{bm.itemType}</h3>
              <div className="text-xs text-gray-500 mt-1">{bm.itemId}</div>
            </div>
            <div className="text-xs text-gray-400">{bm.createdAt || ''}</div>
          </div>
        ))}
        {!loading && bookmarks.length === 0 && (
          <div className="text-center text-gray-500">No bookmarks yet.</div>
        )}
      </div>
    </div>
  );
}
