/**
 * Route File: src/app/dashboard/performance/page.tsx
 * Auto-generated by dashboard route script
 */
"use client";

import React, { useEffect, useState } from 'react';
import Link from 'next/link';

interface QuizAttempt {
  id: string;
  payload: any;
  createdAt?: string;
}

export default function PerformancePage() {
  const [attempts, setAttempts] = useState<QuizAttempt[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/dashboard/performance')
      .then((r) => r.json())
      .then((data) => setAttempts(data.quizAttempts || []))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="p-4 space-y-4 mx-auto">
      <div className="flex items-center mb-4">
        <Link href="/dashboard" className="mr-4 text-gray-600">← Back</Link>
        <h1 className="text-xl font-bold">Performance</h1>
      </div>

      {loading && <div className="text-center text-gray-500">Loading...</div>}

      <div className="space-y-3">
        {attempts.map((a) => (
          <div key={a.id} className="bg-white border rounded-xl p-4 shadow-sm">
            <div className="text-sm font-medium text-gray-800">{a.payload?.quizTitle || 'Quiz'}</div>
            <div className="text-xs text-gray-500 mt-1">{a.createdAt}</div>
          </div>
        ))}
        {!loading && attempts.length === 0 && (
          <div className="text-center text-gray-500">No performance data yet.</div>
        )}
      </div>
    </div>
  );
}
