/**
 * Route File: src/app/dashboard/history/page.tsx
 * Auto-generated by dashboard route script
 */
"use client";

import React, { useEffect, useState } from 'react';
import Link from 'next/link';

interface Activity {
  id: string;
  type: string;
  payload: any;
  createdAt?: string;
}

export default function HistoryPage() {
  const [activities, setActivities] = useState<Activity[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/dashboard/history')
      .then((r) => r.json())
      .then((data) => setActivities(data.activities || []))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="p-4 space-y-4 mx-auto">
      <div className="flex items-center mb-4">
        <Link href="/dashboard" className="mr-4 text-gray-600">← Back</Link>
        <h1 className="text-xl font-bold">History</h1>
      </div>

      {loading && <div className="text-center text-gray-500">Loading...</div>}

      <div className="space-y-3">
        {activities.map((act) => (
          <div key={act.id} className="bg-white border rounded-xl p-4 shadow-sm">
            <div className="text-sm font-medium text-gray-800">{act.type}</div>
            <div className="text-xs text-gray-500 mt-1">{act.createdAt}</div>
          </div>
        ))}
        {!loading && activities.length === 0 && (
          <div className="text-center text-gray-500">No history available.</div>
        )}
      </div>
    </div>
  );
}
